export const keywords = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "PHP",
  "HTML",
  "CSS",
  "SASS",
  "Stylus",
  "SQL",
  "NoSQL",
  "React",
  "Vue.js",
  "jQuery",
  "Next.js",
  "Nuxt.js",
  "Express",
  "Tailwind CSS",
  "Bootstrap",
  "Semantic UI",
  "Node.js",
  ".NET",
  "ASP.NET",
  "UML",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Oracle",
  "SQL Server",
  "Firebase",
  "Firestore",
  "Figma",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "InDesign",
  "After Effects",
  "Premiere Pro",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "SVN",
  "Visual Studio Code",
  "Atom",
  "IntelliJ IDEA",
  "Eclipse",
  "NetBeans",
  "Android Studio",
  "Unity",
  "Postman",
  "Insomnia",
  "JIRA",
  "Trello",
  "Asana",
  "Slack",
  "Microsoft Teams",
  "Zoom",
  "Google Meet",
  "WordPress",
  "Docker",
  "GraphQL",
  "Microservices",
  "Testing Frameworks",
  "Continuous Integration",
  "Continuous Deployment",
  "CI/CD",
  "Performance Optimization",
  "Progressive Web Apps",
  "PWAs",
  "Serverless Computing",
  "AWS Lambda",
  "Azure Functions",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Data Structures",
  "Algorithms",
  "Design Patterns",
  "Cybersecurity",
  "Web Accessibility",
  "Performance Tuning",
  "DevOps",
  "Container Orchestration",
  "Machine Learning",
  "Artificial Intelligence",
  "Internet of Things",
  "Blockchain",
  "Cryptocurrency",
];
